In [31]:
import pandas as pd
import joblib

In [11]:
loaded_model = joblib.load(
    r"C:\Users\jidny\OneDrive\Documents\Hiresnix_Internship\Project_1_Accident_Severity_Predictor\model\accident_severity_model.pkl"
)

In [12]:
X = pd.read_csv(
    r"C:\Users\jidny\OneDrive\Documents\Hiresnix_Internship\Project_1_Accident_Severity_Predictor\Dataset\X_prepared.csv"
)

In [13]:
X.head()

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident
0,420,1,0,1,0,0,0,0,3,3,...,2,2,3,2,5,3,7,5,5,9
1,420,1,1,1,4,0,3,11,3,2,...,2,2,3,2,5,3,7,5,5,16
2,420,1,0,1,4,0,0,5,3,6,...,2,2,0,1,1,2,0,5,5,0
3,594,3,0,1,4,0,2,11,0,6,...,2,2,2,0,0,2,0,2,5,1
4,594,3,0,1,4,0,1,17,3,2,...,2,2,3,2,5,3,7,5,5,16

In [14]:
y_data = pd.read_csv(
    r"C:\Users\jidny\OneDrive\Documents\Hiresnix_Internship\Project_1_Accident_Severity_Predictor\Dataset\Y_prepared.csv"
)

In [15]:
y_data.head()

   Accident_severity
0                  2
1                  2
2                  1
3                  2
4                  2

In [16]:
y_data.columns

Index(['Accident_severity'], dtype='object')

In [17]:
y = y_data["Accident_severity"]

In [18]:
y.head()

0    2
1    2
2    1
3    2
4    2
Name: Accident_severity, dtype: int64

In [19]:
severity_map = {
    0: "Slight",
    1: "Serious",
    2: "Fatal"
}

In [20]:
sample = X.iloc[[0]]

In [21]:
sample

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,...,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident
0,420,1,0,1,0,0,0,0,3,3,...,2,2,3,2,5,3,7,5,5,9

In [22]:
prediction = loaded_model.predict(sample)

In [23]:
print("Encoded Prediction:", prediction)

Encoded Prediction: [2]

In [24]:
print(
    "Predicted Severity:",
    severity_map[prediction[0]]
)

Predicted Severity: Fatal

In [25]:
print(
    "Actual Severity:",
    severity_map[y.iloc[0]]
)

Actual Severity: Fatal

In [26]:
predictions = loaded_model.predict(
    X.iloc[:10]
)

In [27]:
print(predictions)

[2 2 1 2 2 2 2 2 2 2]

In [28]:
print(
    y.iloc[:10].values
)

[2 2 1 2 2 2 2 2 2 1]

In [29]:
comparison = pd.DataFrame({
    "Actual": [
        severity_map[value]
        for value in y.iloc[:10].values
    ],
    "Predicted": [
        severity_map[value]
        for value in predictions
    ]
})

comparison

    Actual Predicted
0    Fatal     Fatal
1    Fatal     Fatal
2  Serious   Serious
3    Fatal     Fatal
4    Fatal     Fatal
5    Fatal     Fatal
6    Fatal     Fatal
7    Fatal     Fatal
8    Fatal     Fatal
9  Serious     Fatal

In [30]:
comparison.to_csv(
    r"C:\Users\jidny\OneDrive\Documents\Hiresnix_Internship\Project_1_Accident_Severity_Predictor\Report\sample_predictions.csv",
    index=False
)